import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="font-primary relative flex flex-col min-h-screen text-black">
          <Header />
          <div className="flex-1 mt-[100px]">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
